apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
  namespace: farm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: server
    spec:
      serviceAccountName: farm-serviceaccount
      containers:
      - name: server
        image: eu.gcr.io/zp-zoneprojects/buildkube/farm/server:latest
        ports:
        - containerPort: 8980
      - name: worker
        image: eu.gcr.io/zp-zoneprojects/buildkube/farm/worker:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 22
          name: tcp
