apiVersion: v1
kind: Service
metadata:
  name: remote
  namespace: farm
spec:
  selector:
    k8s-app: server
  ports:
  - port: 8980
    name: http-server
    targetPort: 8980
  - port: 80
    name: http-worker
  - port: 22
    name: tcp-ssh-worker
