apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  namespace: farm
spec:
  replicas: 16
  template:
    metadata:
      labels:
        k8s-app: worker
    spec:
      containers:
      - name: worker
        image: eu.gcr.io/national-archives/buildkube/farm/worker:latest
