apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  namespace: farm
spec:
  replicas: 8
  template:
    metadata:
      labels:
        k8s-app: worker
    spec:
      serviceAccountName: farm-serviceaccount
      containers:
      - name: worker
        image: eu.gcr.io/zp-zoneprojects/buildkube/farm/worker:latest
